"""Shared helpers for Generator adapters.

Module-private (underscored). Anything used by ≥2 generators lives here:

- Markdown table emission
- Confidence-to-emoji mapping (kept in one place so all surfaces agree)
- Crosswalk + inventory loading helpers
- "Do not edit" footer
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from cora_extractors.inventory import Inventory

INVENTORY_GLOB = "standards/*/current/inventory/*.yaml"
CROSSWALK_GLOB = "crosswalks/concepts/*.yaml"

DO_NOT_EDIT_FOOTER = (
    "_Generated by `cora docs build`. Do not edit by hand — "
    "regenerate when the underlying inventories or crosswalks change._\n"
)

# Confidence ordering for stable, comparable rendering across surfaces.
CONFIDENCE_BADGE: dict[str, str] = {
    "exact": "🟢 exact",
    "close": "🟢 close",
    "partial": "🟡 partial",
    "divergent": "🔴 divergent",
    "not_present": "⚪ not_present",
}


@dataclass(frozen=True)
class Crosswalk:
    """Loaded crosswalk YAML (we don't have a pydantic model for it yet)."""

    path: Path
    concept: str
    canonical_definition: str
    aliases: list[str]
    boundary: bool
    mappings: dict[str, dict[str, Any]]
    maintainer: str
    last_reviewed: str
    references: list[str]

    @classmethod
    def from_yaml(cls, path: Path) -> Crosswalk:
        data = yaml.safe_load(path.read_text()) or {}
        return cls(
            path=path,
            concept=data["concept"],
            canonical_definition=data["canonical_definition"],
            aliases=list(data.get("aliases", [])),
            boundary=bool(data.get("boundary", False)),
            mappings=dict(data.get("mappings", {})),
            maintainer=data["maintainer"],
            last_reviewed=str(data["last_reviewed"]),
            references=list(data.get("references", [])),
        )


def load_crosswalks(repo_root: Path) -> list[Crosswalk]:
    return [Crosswalk.from_yaml(p) for p in sorted(repo_root.glob(CROSSWALK_GLOB))]


def load_inventories(repo_root: Path) -> dict[str, list[Inventory]]:
    """Return inventories grouped by standard short name (mits, ibpdi, redi)."""
    grouped: dict[str, list[Inventory]] = {}
    for p in sorted(repo_root.glob(INVENTORY_GLOB)):
        std = p.parts[-4]
        grouped.setdefault(std, []).append(Inventory.from_yaml(p))
    return grouped


def standards_in(crosswalks: Sequence[Crosswalk]) -> list[str]:
    """Return the unique standards referenced across the given crosswalks, sorted."""
    out: set[str] = set()
    for cw in crosswalks:
        out.update(cw.mappings.keys())
    return sorted(out)


def md_table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    """Render a GitHub-flavored Markdown table."""
    parts = ["| " + " | ".join(headers) + " |"]
    parts.append("|" + "|".join(["---"] * len(headers)) + "|")
    for row in rows:
        parts.append("| " + " | ".join(_md_escape(c) for c in row) + " |")
    return "\n".join(parts) + "\n"


def _md_escape(cell: str) -> str:
    """Escape pipes and collapse newlines for Markdown table cells."""
    if cell is None:
        return ""
    s = str(cell).replace("|", "\\|").replace("\n", " ").replace("\r", " ")
    return s


def resolve_field_in_inventories(
    field_path: str, inventories: list[Inventory]
) -> tuple[Inventory, Any] | None:
    """Find (inventory, FieldEntry) where the given path resolves, or None."""
    from cora_extractors.path import resolve as resolve_path

    for inv in inventories:
        fe = resolve_path(field_path, inv)
        if fe is not None:
            return (inv, fe)
    return None
