"""Index generator.

Emits ``README.md`` at the root of ``output_dir`` — the entry point a
reader hits first. Links to the coverage matrix, concept overview, every
concept page, and every inventory page, with per-standard counts.
"""

from __future__ import annotations

from pathlib import Path

from cora_extractors.generators._common import (
    DO_NOT_EDIT_FOOTER,
    load_crosswalks,
    load_inventories,
    normalize_blanks,
)

OUTPUT_PATH = Path("README.md")


class IndexGenerator:
    """Generator adapter for the docs index page."""

    name = "index"

    def generate(self, repo_root: Path, output_dir: Path) -> list[Path]:
        crosswalks = load_crosswalks(repo_root)
        inventories = load_inventories(repo_root)

        parts: list[str] = ["# CORA Generated Documentation\n"]
        parts.append(
            "Browseable view of the committed inventories and crosswalks. "
            "Generated by `cora docs build` from the YAML artifacts under "
            "`standards/` and `crosswalks/`.\n"
        )

        # Crosswalks section
        parts.append("## Crosswalks\n")
        if crosswalks:
            parts.append(
                "- [Coverage Matrix](coverage-matrix.md) — "
                "concepts × standards at a glance"
            )
            parts.append(
                "- [Concept Overview](concept-overview.md) — "
                "Mermaid graph of every concept and its mappings"
            )
            parts.append(
                "- [Adoption Briefings](adoption/README.md) — "
                "per-standard-pair guides for adopting an additional standard"
            )
            parts.append("\n### Concepts\n")
            for cw in sorted(crosswalks, key=lambda c: c.concept):
                tag = " — boundary" if cw.boundary else ""
                parts.append(f"- [{cw.concept}](concepts/{cw.concept}.md){tag}")
            parts.append("")
        else:
            parts.append("_No crosswalks committed yet._\n")

        # Inventories section
        parts.append("## Inventories\n")
        for std in sorted(inventories.keys()):
            invs = inventories[std]
            total_types = sum(len(i.types) for i in invs)
            total_fields = sum(len(i.fields) for i in invs)
            parts.append(
                f"### {std.upper()} — {len(invs)} module"
                f"{'s' if len(invs) != 1 else ''}, "
                f"{total_types} types, {total_fields} fields\n"
            )
            for inv in sorted(invs, key=lambda i: i.module):
                parts.append(
                    f"- [{inv.module}](inventories/{std}/{inv.module}.md) — "
                    f"{len(inv.types)} types / {len(inv.fields)} fields"
                )
            parts.append("")

        parts.append(DO_NOT_EDIT_FOOTER)

        out = output_dir / OUTPUT_PATH
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(normalize_blanks("\n".join(parts)))
        return [OUTPUT_PATH]
