type_sheets:
  Address Type: AddressType
  InvoiceType: InvoiceType
  Payment Type: PaymentType
  Invoice Detail Type: InvoiceDetailType
  Memo Type: MemoType
  SkuType: SkuType
  InsuranceType: InsuranceType
