"""CSV + Markdown writers for the concepts analyzer outputs.

All writers are pure functions of their inputs and produce byte-identical
output across runs (deterministic sort, `\\n`-only line endings, no
timestamps in the payload). This is what makes ``cora concepts check``
work as a drift gate.
"""

from __future__ import annotations

from collections import Counter
from io import StringIO
from pathlib import Path

from cora_extractors.concepts.census import CensusRow
from cora_extractors.concepts.suggest import Cluster
from cora_extractors.generators._common import (
    DO_NOT_EDIT_FOOTER,
    md_table,
    normalize_blanks,
)

OUTPUT_DIR = Path("docs/concepts-analysis")
CENSUS_CSV = "field-census.csv"
CENSUS_MD = "field-census.md"
SUGGESTIONS_MD = "suggestions.md"

CSV_COLUMNS = (
    "standard",
    "module",
    "type_name",
    "path",
    "leaf_name",
    "range",
    "cardinality",
    "definition",
)


def write_census_csv(rows: list[CensusRow], out_dir: Path) -> Path:
    """Write the full census as CSV. Newline-stable across platforms."""
    import csv

    out_dir.mkdir(parents=True, exist_ok=True)
    buf = StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(CSV_COLUMNS), lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({col: getattr(row, col) for col in CSV_COLUMNS})
    out = out_dir / CENSUS_CSV
    out.write_text(buf.getvalue())
    return out


def write_census_summary(rows: list[CensusRow], out_dir: Path) -> Path:
    """Write a human-readable summary of the census (counts, not full rows)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    by_std: Counter[str] = Counter()
    by_module: Counter[tuple[str, str]] = Counter()
    for row in rows:
        by_std[row.standard] += 1
        by_module[(row.standard, row.module)] += 1

    parts = ["# Field census\n"]
    parts.append(
        f"Flat catalogue of every leaf field across the committed inventory corpus. "
        f"**{len(rows):,}** rows across {len(by_std)} standards. Full CSV at "
        f"[`field-census.csv`](field-census.csv).\n"
    )
    parts.append("## Counts by standard\n")
    parts.append(
        md_table(
            ["Standard", "Fields"],
            [[std.upper(), f"{count:,}"] for std, count in sorted(by_std.items())],
        )
    )
    parts.append("## Counts by module\n")
    parts.append(
        md_table(
            ["Standard", "Module", "Fields"],
            [
                [std.upper(), module, f"{count:,}"]
                for (std, module), count in sorted(by_module.items())
            ],
        )
    )
    parts.append("\n" + DO_NOT_EDIT_FOOTER)
    out = out_dir / CENSUS_MD
    out.write_text(_finalize("\n".join(parts)))
    return out


def write_suggestions(clusters: list[Cluster], out_dir: Path) -> Path:
    """Write the candidate-cluster Markdown report."""
    out_dir.mkdir(parents=True, exist_ok=True)
    uncovered = [c for c in clusters if c.already_covered_by is None]
    covered = [c for c in clusters if c.already_covered_by is not None]

    parts = ["# Candidate concept clusters\n"]
    parts.append(
        f"Generated by `cora concepts suggest`. **{len(clusters)}** clusters where the "
        f"same normalized leaf name appears across at least two standards. The tool "
        f"proposes; the editorial pass confirms.\n"
    )
    parts.append(
        f"- **{len(uncovered)}** clusters not yet covered by an existing crosswalk.\n"
        f"- **{len(covered)}** clusters already covered.\n"
    )
    parts.append(
        "Each cluster lists its member fields, the standards touched, and the average "
        "cross-standard definition-Jaccard as a quality signal. Higher Jaccard means "
        "the source-side definitions overlap more, which usually correlates with a "
        "cleaner mapping.\n"
    )

    parts.append("## Uncovered candidates\n")
    if uncovered:
        for cluster in uncovered:
            parts.append(_render_cluster(cluster))
    else:
        parts.append(
            "_No uncovered candidates. The corpus is fully crosswalked for these clusters._\n"
        )

    parts.append("## Already covered (for reference)\n")
    if covered:
        for cluster in covered:
            parts.append(_render_cluster(cluster))
    else:
        parts.append("_No covered clusters yet — this section grows as crosswalks land._\n")

    parts.append("\n" + DO_NOT_EDIT_FOOTER)
    out = out_dir / SUGGESTIONS_MD
    out.write_text(_finalize("\n".join(parts)))
    return out


def _render_cluster(cluster: Cluster) -> str:
    stds = ", ".join(s.upper() for s in cluster.standards)
    # Blank line after the heading per markdownlint MD022.
    header = f"### `{cluster.canonical_key}` ({len(cluster.standards)} standards: {stds})\n\n"
    quality = f"_Average cross-standard definition Jaccard: {cluster.avg_def_jaccard:.2f}_\n"
    if cluster.already_covered_by is not None:
        status = f"_Already covered by crosswalk: **{cluster.already_covered_by}**_\n"
    else:
        status = "_Suggested action: review and scaffold a crosswalk._\n"
    rows = [
        [r.standard.upper(), r.module, r.path, r.cardinality, _short(r.definition)]
        for r in cluster.rows
    ]
    table = md_table(["Standard", "Module", "Path", "Cardinality", "Definition"], rows)
    return header + quality + status + "\n" + table + "\n"


def _finalize(text: str) -> str:
    """Collapse 3+ consecutive newlines and ensure exactly one trailing newline."""
    return normalize_blanks(text).rstrip("\n") + "\n"


def _short(text: str, limit: int = 120) -> str:
    """Collapse whitespace and truncate long definitions for table readability."""
    collapsed = " ".join(text.split())
    if len(collapsed) <= limit:
        return collapsed
    return collapsed[: limit - 1] + "…"
